[tool.poetry]
name = "ansible-docker"
version = "0.2.1"
description = "Ansible role to install/configure Docker"
authors = ["Larry Smith Jr. <mrlesmithjr@gmail.com>", "xiaoyao9184"]

[tool.poetry.dependencies]
# poetry use virtualenv and drop python < 3.7 support
# see https://virtualenv.pypa.io/en/latest/changelog.html#v20-27-0-2024-10-17
python = "^3.8"
ansible = "^4.6.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "^1.5.6"
flake8 = "^3.9.0"
pycodestyle = "^2.7.0"
pylint = "^2.7.3"
tox = "^3.23.0"
black = "^21.9b0"
ansible-lint = "^5.1.3"
mkdocs = "^1.1.2"
# molecule > 4.0.0 support skip role-name check
# see https://github.com/ansible/ansible-compat/issues/78
molecule = {extras = ["docker"], version = "^4.0.0"}
yamllint = "^1.26.0"
mkdocs-material = "^7.3.0"
# lock version
# see https://github.com/docker/docker-py/issues/3256
requests = "<=2.32.0"
pre-commit = "<=3.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
