---
# skip role name check
# see https://github.com/ansible/ansible-compat/issues/78
role_name_check: 1
dependency:
  name: galaxy
  # need update `community.docker` support `cgroupns_mode` by molecule-plugins[docker]
  enabled: true
  options:
    role-file: requirements.yml
driver:
  name: docker
# remove in molecule v5
# see https://github.com/ansible/molecule/discussions/3914
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: alpine318
    image: fauust/docker-systemd:alpine-3.18
    privileged: true
    command: /sbin/init
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      # fix `Failed to connect to bus: No such file or directory`
      # see https://www.jeffgeerling.com/blog/2022/docker-and-systemd-getting-rid-dreaded-failed-connect-bus-error
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # fix the startup issue `docker run -it -v /sys/fs/cgroup:/sys/fs/cgroup:rw iamenr0s/docker-rockylinux8-ansible /usr/sbin/init`
    # see https://github.com/ansible/molecule/discussions/3349
    # must community.docker > 3.0.0 ansible > 7.0.0
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
    cleanup: ../shared/cleanup.yml
verifier:
  name: ansible
