---
- name: alpine | Ensuring Edge Repo Is Enabled
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    regexp: "^http://dl-cdn.alpinelinux.org/alpine/edge/community"
    line: http://dl-cdn.alpinelinux.org/alpine/edge/community
    state: present
  become: true
  register: _apk_repos_updated
  until: _apk_repos_updated is successful

- name: alpine | Updating APK Cache # noqa: no-handler
  community.general.apk:
    update_cache: true
  become: true
  register: result
  until: result is successful
  when: _apk_repos_updated['changed']

- name: alpine | Installing Docker
  community.general.apk:
    name: docker
    state: present
  become: true
  register: result
  until: result is successful
