---
- name: alpine | Ensuring Edge Repo Is Enabled
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    regexp: "^{{ docker_alpine_apk_repo_url }}"
    line: "{{ docker_alpine_apk_repo_url }}"
    state: present
  become: true
  register: _apk_repos_updated
  until: _apk_repos_updated is successful

- name: alpine | Updating APK Cache # noqa: no-handler
  ansible.builtin.apk:
    update_cache: true
  become: true
  register: result
  until: result is successful
  when: _apk_repos_updated['changed']

- name: alpine | Checking for existing docker # noqa: no-handler
  ansible.builtin.command: "apk info -e '{{ docker_alpine_apk_check_package }}'"
  ignore_errors: true
  register: has_docker
  changed_when: false

- name: alpine | Installing docker versioned
  ansible.builtin.apk:
    name: "{{ docker_alpine_apk_present_versioned_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_version | lower != "latest" and docker_version | lower != "any"

- name: alpine | Installing Docker
  ansible.builtin.apk:
    name: "{{ docker_alpine_apk_present_latest_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version | lower == "latest"
    or (docker_version | lower == "any" and has_docker is failed)
