---
- name: config_docker | Include tasks for Linux
  ansible.builtin.include_tasks: config_docker_linux.yml
  when:
    - ansible_os_family != 'Windows'

- name: config_docker | Include tasks for Windows
  ansible.builtin.include_tasks: config_docker_windows.yml
  when:
    - ansible_os_family == 'Windows'
