---
- name: debian | Updating apt-cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: result
  until: result is successful

- name: debian | Installing pre-reqs
  ansible.builtin.apt:
    name: "{{ docker_debian_apt_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_debian_apt_pre_reqs | default([],true) | length > 0

- name: debian | Installing repository by apt-key apt-repository
  ansible.builtin.include_tasks: debian_repository_apt.yml
  when:
    - docker_debian_repo_type | default('apt') == 'apt'

- name: debian | Installing repository by deb822-repository
  ansible.builtin.include_tasks: debian_repository_deb822.yml
  when:
    - docker_debian_repo_type | default('apt') == 'deb822'

# We remove docker-engine as this is old package to install.
# The new package is docker-ce
- name: debian | Uninstalling old docker packages (if exists)
  apt:
    name: "{{ docker_debian_apt_absent_packages }}"
    state: absent
    purge: true
  become: true
  register: result
  until: result is successful

- name: debian | Checking for existing docker # noqa 305
  ansible.builtin.shell: "dpkg-query -W '{{ docker_debian_apt_check_package }}'"
  ignore_errors: true
  register: has_docker
  changed_when: false

- name: debian | Installing docker
  ansible.builtin.apt:
    name: "{{ docker_debian_apt_present_versioned_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_version|lower != "latest"
    - has_docker is failed

- name: debian | Installing docker
  ansible.builtin.apt:
    name: "{{ docker_debian_apt_present_latest_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_version|lower == "latest"
    - has_docker is failed

- name: debian | Checking For /etc/default/grub
  ansible.builtin.stat:
    path: /etc/default/grub
  register: _docker_grub_check

- name: debian | Setting grub memory limit (if set)
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"'
  register: grub_updated
  become: true
  when:
    - _docker_grub_check['stat']['exists']
    - docker_debian_set_grub_memory_limit is defined
    - docker_debian_set_grub_memory_limit

- name: debian | Updating grub (if updated) # noqa 503
  ansible.builtin.command: update-grub
  become: true
  when: grub_updated['changed']

- name: debian | Installing bridge-utils
  ansible.builtin.apt:
    name: bridge-utils
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_install_bridge_utils is defined
    - docker_install_bridge_utils
