---
- name: Images | Ensuring Docker images are present
  community.docker.docker_image:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] }}"
    source: pull
  become: true
  loop: "{{ docker_images }}"
