---
- name: images | Ensuring docker images are present
  community.docker.docker_image:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] }}"
    # without `source` will error: 'state is present but all of the following are missing: source'
    source: pull
  become: true
  loop: "{{ docker_images }}"
