---
# tasks file for ansible-docker
- name: Load OS-specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - main.yml
      paths:
        - 'vars'

- include_tasks: set_facts.yml

- include_tasks: alpine.yml
  when: ansible_os_family == "Alpine"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config_docker.yml
  when: docker_config_service|bool

- include_tasks: service.yml

- name: Flush handlers
  meta: flush_handlers

- include_tasks: users.yml
  when:
    - docker_config_users|bool
    - docker_users is defined

- include_tasks: images.yml
  when:
    - docker_pull_images|bool
    - docker_images is defined
