---
# tasks file for ansible-docker
- name: Include set_facts tasks
  ansible.builtin.include_tasks:
    file: set_facts.yml

- name: Include Alpine tasks
  ansible.builtin.include_tasks:
    file: alpine.yml
  when: ansible_os_family == "Alpine"

- name: Include Debian tasks
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_os_family == "Debian"

- name: Include RedHat tasks
  ansible.builtin.include_tasks:
    file: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include ZFS tasks
  ansible.builtin.include_tasks:
    file: zfs.yml
  when: docker_storage_driver == "zfs"

- name: Include config_docker tasks
  ansible.builtin.include_tasks:
    file: config_docker.yml
  when: docker_config_service | bool

- name: Include service tasks
  ansible.builtin.include_tasks:
    file: service.yml

- name: Include users tasks
  ansible.builtin.include_tasks:
    file: users.yml
  when:
    - docker_config_users is defined
    - docker_config_users | bool

- name: Include images tasks
  ansible.builtin.include_tasks:
    file: images.yml
  when:
    - docker_manage_images | bool
    - docker_images is defined
