---
# tasks file for ansible-docker
- name: Push CounterAPI
  ansible.builtin.uri:
    url: https://counterapi.com/api/xiaoyao9184.github.com/view/ansible-role-docker
    status_code:
      - 200
    timeout: 60
  failed_when: false
  changed_when: false

- name: Include fact_etc
  ansible.builtin.include_tasks: fact_etc.yml

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "distribution={{ ansible_distribution }}+version={{ ansible_distribution_version | default('NONE') }}.yml"
        - "distribution={{ ansible_distribution }}+release={{ ansible_distribution_release | default('NONE') }}.yml"
        - "distribution={{ ansible_distribution }}+major={{ ansible_distribution_major_version }}.yml"
        - "distribution={{ ansible_distribution }}.yml"
        - "os-family={{ ansible_os_family }}.yml"
        - main.yml
      paths:
        - '{{ docker_os_specific_vars_path }}'
        - 'vars'
  when:
    - docker_os_specific_vars_included | default(true)

- name: Include fact_pkg
  ansible.builtin.include_tasks: fact_pkg.yml

- name: Include alpine
  ansible.builtin.include_tasks: alpine.yml
  when: ansible_os_family == "Alpine"

- name: Include debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include redhat
  ansible.builtin.include_tasks: redhat.yml
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "Rocky"

- name: Include suse
  ansible.builtin.include_tasks: suse.yml
  when:
    - ansible_os_family == "Suse"

- name: Include dsm
  ansible.builtin.include_tasks: dsm.yml
  when:
    - >
      ansible_facts.cmdline.syno_hw_version is defined
      or docker_service_name == "pkg-Docker-dockerd.service"
      or docker_service_name == "pkg-ContainerManager-dockerd.service"

- name: Include openwrt
  ansible.builtin.include_tasks: openwrt.yml
  when:
    - ansible_os_family == "OpenWrt"

- name: Include windows
  ansible.builtin.include_tasks: windows.yml
  when:
    - ansible_os_family == "Windows"

- name: Include config_docker
  ansible.builtin.include_tasks: config_docker.yml
  when: docker_config_service | bool

- name: Include service
  ansible.builtin.include_tasks: service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Include users
  ansible.builtin.include_tasks: users.yml
  when:
    - docker_config_users | bool
    - docker_users is defined

- name: Include images
  ansible.builtin.include_tasks: images.yml
  when:
    - docker_pull_images | bool
    - docker_images is defined
