---
# tasks file for ansible-docker
- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ docker_os_specific_vars_file | default('/always_nonexistent', true) }}"
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - main.yml
      paths:
        - 'vars'

- name: Include set_facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Include alpine
  ansible.builtin.include_tasks: alpine.yml
  when: ansible_os_family == "Alpine"

- name: Include debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include redhat
  ansible.builtin.include_tasks: redhat.yml
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "Rocky"

- name: Include suse
  ansible.builtin.include_tasks: suse.yml
  when:
    - ansible_os_family == "Suse"

- name: Include config_docker
  ansible.builtin.include_tasks: config_docker.yml
  when: docker_config_service | bool

- name: Include service
  ansible.builtin.include_tasks: service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Include users
  ansible.builtin.include_tasks: users.yml
  when:
    - docker_config_users | bool
    - docker_users is defined

- name: Include images
  ansible.builtin.include_tasks: images.yml
  when:
    - docker_pull_images | bool
    - docker_images is defined
