---
- name: redhat_repository_dnf | Installing Docker
  ansible.builtin.dnf:
    name: "{{ docker_redhat_package_present_versioned_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version | lower != "latest"

- name: redhat_repository_dnf | Installing Docker
  ansible.builtin.dnf:
    name: "{{ docker_redhat_package_present_latest_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version | lower == "latest"
