---
- name: redhat_repository_dnf | Checking for existing docker # noqa: command-instead-of-module
  ansible.builtin.command: "rpm -q '{{ docker_redhat_yum_check_package }}'"
  ignore_errors: true
  register: has_docker
  changed_when: false

- name: redhat_repository_dnf | Installing Docker versioned
  ansible.builtin.dnf:
    name: "{{ docker_redhat_package_present_versioned_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_version | lower != "latest" and docker_version | lower != "any"

- name: redhat_repository_dnf | Installing Docker latest
  ansible.builtin.dnf:
    name: "{{ docker_redhat_package_present_latest_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version | lower == "latest"
    or (docker_version | lower == "any" and has_docker is failed)
