---
- name: redhat | Uninstalling Old Docker Package (if exists)
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-engine
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
    state: absent
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Uninstalling Old Docker Package (if exists)
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-engine
      - docker-engine-selinux
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
    state: absent
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Adding Docker repo
  template:
    src: etc/yum.repos.d/docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
    mode: 0644
  become: true
  when: >
    ansible_distribution != "Fedora" or
    (ansible_distribution == "Fedora" and
    ansible_distribution_version is version('31', '<'))

- name: redhat | Installing Docker
  package:
    name:
      - "docker-ce-{{ docker_version_redhat }}"
      - containerd.io
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version|lower != "latest" and
    (ansible_distribution != "Fedora" or
    (ansible_distribution == "Fedora" and
    ansible_distribution_version is version('31', '<')))

- name: redhat | Installing Docker
  package:
    name:
      - docker-ce
      - containerd.io
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version|lower == "latest" and
    (ansible_distribution != "Fedora" or
    (ansible_distribution == "Fedora" and
    ansible_distribution_version is version('31', '<')))

- name: redhat | Installing bridge-utils
  package:
    name: bridge-utils
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_install_bridge_utils is defined
    - docker_install_bridge_utils

# https://fedoramagazine.org/docker-and-fedora-32/
- name: redhat | Installing Docker
  package:
    name:
      - docker-compose
      - moby-engine
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_version is version('31', '>=')

# https://fedoramagazine.org/docker-and-fedora-32/
- name: redhat | Configuring FirewallD
  firewalld:
    interface: docker0
    permanent: true
    state: enabled
    zone: trusted
  become: true
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_version is version('32', '>=')

# https://fedoramagazine.org/docker-and-fedora-32/
- name: redhat | Configuring FirewallD
  firewalld:
    masquerade: "true"
    permanent: true
    state: enabled
    zone: FedoraWorkstation
  become: true
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_version is version('32', '>=')
