---
- name: redhat_repository_yum | Adding Docker repo
  ansible.builtin.template:
    src: etc/yum.repos.d/docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
    mode: 0644
  become: true

- name: redhat_repository_yum | Installing Docker
  ansible.builtin.package:
    name: "{{ docker_redhat_package_present_versioned_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version | lower != "latest"

- name: redhat_repository_yum | Installing Docker
  ansible.builtin.package:
    name: "{{ docker_redhat_package_present_latest_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version | lower == "latest"
