---
- name: redhat | Uninstalling Old Docker Package (if exists)
  ansible.builtin.package:
    name: "{{ docker_redhat_package_absent_packages }}"
    state: absent
  become: true
  register: result
  until: result is successful

- name: redhat | Installing docker by yum
  ansible.builtin.include_tasks: redhat_repository_yum.yml
  when:
    - >
      ansible_distribution != "Fedora" or
      (ansible_distribution == "Fedora" and
      ansible_distribution_version is version('31', '<'))

- name: redhat | Installing docker for fedora31
  ansible.builtin.include_tasks: redhat_repository_fedora31.yml
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_version is version('31', '>=')

- name: redhat | Installing bridge-utils
  ansible.builtin.package:
    name: bridge-utils
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_install_bridge_utils is defined
    - docker_install_bridge_utils
