---
- name: service | Ensuring Docker Service Is Started And Enabled On Boot
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true
  become: true
  when:
    - docker_service_name is defined
