---
# see https://docs.docker.com/engine/install/sles/
- name: suse | Uninstalling Old Docker Package (if exists)
  community.general.zypper:
    name: "{{ docker_suse_zypper_absent_packages }}"
    state: absent
  become: true
  register: result
  until: result is successful
  when:
    - docker_suse_package_absent_packages | default([], true) | length > 0

- name: suse | Adding repository
  loop: "{{ docker_suse_zypper_repo_info | default([], true) }}"
  community.general.zypper_repository:
    name: "{{ item.name | default(omit) }}"
    repo: "{{ item.repo }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: suse | Installing Docker
  community.general.zypper:
    name: "{{ docker_suse_zypper_present_latest_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
