---
# see https://docs.docker.com/engine/install/sles/
- name: suse | Uninstalling Old Docker Package (if exists)
  ansible.builtin.zypper:
    name: "{{ docker_suse_zypper_absent_packages }}"
    state: absent
  become: true
  register: result
  until: result is successful
  when:
    - docker_suse_package_absent_packages | default([], true) | length > 0

- name: suse | Adding repository
  loop: "{{ docker_suse_zypper_repo_info | default([], true) }}"
  ansible.builtin.zypper_repository:
    name: "{{ item.name | default(omit) }}"
    repo: "{{ item.repo }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: suse | Checking for existing docker # noqa: command-instead-of-module
  ansible.builtin.command: "rpm -q '{{ docker_suse_zypper_check_package }}'"
  ignore_errors: true
  register: has_docker
  changed_when: false

- name: suse | Installing docker versioned
  ansible.builtin.zypper:
    name: "{{ docker_suse_zypper_present_versioned_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_version | lower != "latest" and docker_version | lower != "any"

- name: suse | Installing Docker latest
  ansible.builtin.zypper:
    name: "{{ docker_suse_zypper_present_latest_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    docker_version | lower == "latest"
    or (docker_version | lower == "any" and has_docker is failed)
