---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Info docker # noqa: command-instead-of-module
    ansible.builtin.command: "dpkg-query -W 'docker-ce'"
    ignore_errors: true
    register: info_docker
    changed_when: false

  - name: Ensure version is 17.03.0
    ansible.builtin.assert:
      that:
        - info_docker.stdout is search("17.03.0")
      fail_msg: "version must be to 17.03.0"
