---
# handlers file for ansible-docker
- name: Restart docker
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: restarted
  become: true
  when:
    - docker_service_name is defined
