---
- name: Prepare
  hosts: localhost
  connection: local
  tasks:
    - name: install sshpass
      ansible.builtin.package:
        name: sshpass
        state: present
      become: true
      failed_when: false

- name: Include shared prepare
  ansible.builtin.import_playbook: ../shared/prepare.yml
