---
- name: Converge
  hosts: all
  vars:
    docker_debian_set_grub_memory_limit: false
    docker_version: latest
  pre_tasks:
    # see https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
    - name: Wait for systemd to complete initialization. # noqa 303
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when:
        - ansible_service_mgr == 'systemd'
        - ansible_distribution == 'Fedora'
      changed_when: false
  tasks:
    - name: Include docker
      ansible.builtin.include_role:
        name: docker
