---
- name: Prepare
  hosts: all
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print version distribution facts
      ansible.builtin.debug:
        msg:
          - "{{ ansible_os_family }}"
          - "{{ ansible_pkg_mgr }}"
          - "{{ ansible_distribution }}"
          - "{{ ansible_distribution_major_version }}"
          - "{{ ansible_distribution_release }}"
          - "{{ ansible_python_version }}"
