---
- name: Prepare
  hosts: all
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print version distribution facts
      ansible.builtin.debug:
        msg:
          - "os-family={{ ansible_os_family }}"
          - "distribution={{ ansible_distribution }}"
          - "distribution={{ ansible_distribution }}+major={{ ansible_distribution_major_version | default('NONE') }}"
          - "distribution={{ ansible_distribution }}+release={{ ansible_distribution_release | default('NONE') }}"
          - "distribution={{ ansible_distribution }}+version={{ ansible_distribution_version | default('NONE') }}"
          - "python={{ ansible_python_version | default('NONE') }}"
          - "pkg={{ ansible_pkg_mgr | default('NONE') }}"

    # fix apt `Unable to locate package`
    # molecule docker task `Build an Ansible compatible image (new)`
    # run `rm -rf /var/lib/apt/lists/*` in dockerfile will make `apt update` cache clean
    - name: Updating apt-cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"
