---
# skip role name check
# see https://github.com/ansible/ansible-compat/issues/78
role_name_check: 1
dependency:
  name: galaxy
  # need update `community.docker` support `cgroupns_mode` by molecule-plugins[docker]
  enabled: true
  options:
    role-file: requirements.yml
driver:
  name: docker
# remove in molecule v5
# see https://github.com/ansible/molecule/discussions/3914
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: config-service
    image: jrei/systemd-ubuntu:24.04
    privileged: true
    command: /lib/systemd/systemd
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      # fix https://github.com/ansible/molecule/issues/3094
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
    prepare: ../shared/prepare.yml
    cleanup: ../shared/cleanup.yml
verifier:
  name: ansible
