FROM jrei/systemd-centos:7

# skip `Build an Ansible compatible image (new)` so we need install missing packages
# see https://github.com/ansible-community/molecule-docker/blob/acb7d4ef0ea83d822f01adf26af543fa0817d5bd/src/molecule_docker/playbooks/create.yml#L65
# see https://github.com/ansible-community/molecule-docker/blob/acb7d4ef0ea83d822f01adf26af543fa0817d5bd/src/molecule_docker/playbooks/Dockerfile.j2#L17
RUN sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/^#.*baseurl=http/baseurl=http/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/*.repo && \
    yum makecache && \
    yum install -y sudo epel-release

# fix `Failed to create symlink /sys/fs/cgroup/net_cls: Operation not permitted`
# centos7 systemctl use cgroup v1 not work on cgroup v2 host
# see https://github.com/docker/for-mac/issues/6073
RUN curl -o /etc/yum.repos.d/jsynacek-systemd-centos-7.repo \
    https://copr.fedorainfracloud.org/coprs/jsynacek/systemd-backports-for-centos-7/repo/epel-7/jsynacek-systemd-backports-for-centos-7-epel-7.repo --insecure && \
    yum update -y systemd && \
    yum clean all
