---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    package: ContainerManager
  tasks:
    - name: Read daemon.json
      ansible.builtin.slurp:
        src: "/var/packages/{{ package }}/etc/dockerd.json"
      register: daemon_json_content
      become: true

    - name: Parse JSON and check values
      ansible.builtin.set_fact:
        daemon_json: "{{ daemon_json_content['content'] | b64decode | from_json }}"

    - name: Ensure data-root is defined
      ansible.builtin.assert:
        that:
          - daemon_json['data-root'] is defined
          - daemon_json['data-root'] == "/var/packages/" + package + "/var/docker"
        fail_msg: "'data-root' must be set to '/var/packages/{{ package }}/var/docker'"

    - name: Ensure insecure-registries contains http://nexus.lan:8082
      ansible.builtin.assert:
        that:
          - "'insecure-registries' in daemon_json"
          - "'http://nexus.lan:8082' in daemon_json['insecure-registries']"
        fail_msg: "'http://nexus.lan:8082' is missing from insecure-registries in /var/packages/{{ package }}/etc/dockerd.json"
